TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += vac_ctrl_tpg300_500.db
DB += vac_gauge_tpg300.db
DB += vac_gauge_tpg300_relay.db
DB += vac_gauge_tpg500.db

DB += vac_ctrl_tpg300_500.proto

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

