TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this


DB += devTPGx00.db
DB += devTPG3xx.db

DB += devTPG300.db
DB += devTPG500.db
DB += test.db

DB += TPG300_base.db
DB += TPG300_channels.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

