TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devTPGx00.proto
DATA += devTPG300.proto
DATA += devTPG500.proto


# DB += unit_setter.db
# DB += TPG300_switching_functions.db
# DB += TPG300_function_statuses.db
# DB += TPG300_switching_functions_rb_error_setter.db
# DB += TPG300_function_statuses_error_setter.db



#=======================================
include $(TOP)/configure/RULES
