TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devTPGx00.proto
DATA += devTPG300.proto
DATA += devTPG500.proto

DB += devTPGx00.db
DB += devTPG300.db
DB += devTPG500.db

DB += TPG300_channels.db
# DB += unit_setter.db
DB += TPG300_switching_functions_rb_AB.db
DB += TPG300_switching_functions_rb.db
DB += TPG300_switching_functions.db
DB += TPG300_function_statuses.db
# DB += TPG300_switching_functions_rb_error_setter.db
# DB += TPG300_function_statuses_error_setter.db

DB += tpg26x.db
DB += tpg36x.db
DATA += TPG26x.proto
DATA += TPG36x.proto


#=======================================
include $(TOP)/configure/RULES
